server:
  port: 8888
  address: 127.0.0.1
mybatis:
  config-location: classpath:conf/mybatis-conf.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    local-cache-scope: session
    cache-enabled: true
spring:
  #  ?????
  datasource:
    url: jdbc:mysql://localhost:3306/docker_cloud
    username: root
    password: 123456789
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
docker-cloud:
  userName: "dockerxylyjy"
  passWord: "docker@123789"
  email: "xylyjy@gmail.com"
#  host: "unix:///var/run/docker.sock"
  host: "tcp://8.130.92.152:2375"
  url: "https://index.docker.io/v1/"
