server:
  port: 8888
  address: 192.168.0.107
mybatis:
  config-location: classpath:conf/mybatis-conf.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-unknown-column-behavior: warning
    local-cache-scope: session
    cache-enabled: true
spring:
  #  ?????
  datasource:
    url: jdbc:mysql://localhost:3306/dockercloud
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver